name: flutternaut_frontend_webapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependency_overrides:
  google_fonts: 4.0.2

dependencies:
  flutter:
    sdk: flutter

  animations: 2.0.11
  auto_route: 8.3.0
  clipboard: 0.1.3
  cupertino_icons: 1.0.6
  equatable: 2.0.5
  file_picker: 8.0.6
  flutter_animate: 4.5.0
  flutter_bloc: 8.1.4
  flutter_email_sender: 6.0.3
  flutter_localizations:
    sdk: flutter
  get_it: 7.7.0
  intl: any
  path_provider: 2.1.2
  rxdart: 0.27.7
  universal_html: 2.2.4

dev_dependencies:
  auto_route_generator: 8.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  assets:
    - pubspec.yaml
    - fonts/
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200

  uses-material-design: true
flutter_intl:
  enabled: true

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icons/flutternaut.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
